name: Run

on:
    push:
        branches:
            - main
    workflow_dispatch: ~
    schedule:
      - cron: '0 0 * * *'


jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cache Composer
              id: cache-composer
              uses: actions/cache@v3
              with:
                path: vendor
                key: ${{ hashFiles('composer.lock') }}
            - name: Composer install
              run: docker-compose run composer install
            - name: Run
              run: docker-compose run ./application.php app:get-best-theme-team