name: Run

on:
    push:
        branches:
            - main
    workflow_dispatch: ~
    pull_request:
        branches:
            - main
    schedule:
      - cron: '0 0 * * *'


jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Build
              run: ./bin/build
            - name: Run
              run: ./bin/run-and-view
            - name: Archive artifacts
              uses: actions/upload-artifact@v3
              with:
                name: get-best-theme-team
                path: ./files
